title: Year of the Geek
email: john.mahlman@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  'Good beer, crappy code'
baseurl: "/" # the subpath of your site, e.g. /blog
url: 'https://jmahlman.github.io' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: floydiandroid
github_username:  jmahlman

google_analytics: UA-5742240-2

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-twitter-plugin
  - jekyll-remote-theme
  - jekyll-seo-tag

# Build settings
# theme: minima
# theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll


plainwhite:
  name: Year of the Geek
  tagline: Good beer, crappy code
  date_format: "%b %-d, %Y"
  disqus_shortname: yotg-git
  portfolio_image: "assets/portfolio.png"
  dark_mode: true
  search: true
  sitemap: true
  social_links:
    twitter: floydiandroid
    github: jmahlman
    linkedIn: in/john-mahlman-iv-58a88450 # format: locale/username
  navigation:
    - title: About
      url: "/about"
    - title: Feed
      url: "/feed.xml"
    - title: Contact
      url: "/contact"

permalink: pretty
show_excerpts: true
# Disqus Comments
# disqus:
#     # Leave shortname blank to disable comments site-wide.
#     # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
#     shortname: yotg-git

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
